FROM osrf/ros:noetic-desktop-full

RUN apt-get update && apt-get install -y nano python3-catkin-tools python3-pip ros-noetic-octomap-msgs ros-noetic-octomap-ros protobuf-compiler libgoogle-glog-dev liblapacke-dev
RUN pip3 install osrf-pycommon